version: '3.8'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: busapp
      POSTGRES_PASSWORD: buspass123
      POSTGRES_DB: busstats
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U busapp -d busstats"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://busapp:buspass123@postgres:5432/busstats
      NODE_ENV: development
      API_KEY: fad204d3-433c-4355-8d38-de1e2186fe58
      BUS_LINE: "321"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend